# Generated by Django 3.0.8 on 2020-08-02 13:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(blank=True, max_length=16)),
                ('drink_time', models.DateTimeField(default=datetime.datetime(2020, 8, 2, 13, 37, 21, 10078, tzinfo=utc))),
                ('volume', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
