# Generated by Django 3.1 on 2020-08-06 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 19, 40, 4, 184934, tzinfo=utc)),
        ),
    ]
