# Generated by Django 3.1 on 2020-08-08 17:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200806_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 17, 20, 57, 155151, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='drink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to=settings.AUTH_USER_MODEL),
        ),
    ]
